name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: phone_catalog_dev
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.11.1' # Define the elixir version [required]
        otp-version: '23.1.1' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install JS dependencies
      uses: Borales/actions-yarn@v2.3.0
      with:
        cmd: --cwd ./assets install
    - name: JS Test
      uses: Borales/actions-yarn@v2.3.0
      with:
        cmd: --cwd ./assets test
    - run: mix local.rebar --force
    - run: mix local.hex --force
    - name: Install Elixir dependencies
      run: mix deps.get
    - name: Run Elixir tests
      run: mix test
  deploy:
    needs: test # Will only run if the test job succeeds
    if: github.ref == 'refs/heads/main' # Only run this job if it is on the master branch

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main # Checkout out master instead of the latest commit
          fetch-depth: 0 # Checkout the whole branch

      - uses: mhanberg/gigalixir-action@249654de0f9389232a5500e027eb9532a20539ca
        with:
          GIGALIXIR_USERNAME: ${{ secrets.GIGALIXIR_USERNAME }}
          GIGALIXIR_PASSWORD: ${{ secrets.GIGALIXIR_PASSWORD }}
          GIGALIXIR_APP: ${{ secrets.GIGALIXIR_APP }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          MIGRATIONS: true  # defaults to true
